# Generated by Django 4.2.4 on 2023-08-13 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ItemShirtApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='item',
        ),
        migrations.AddField(
            model_name='item',
            name='size',
            field=models.ManyToManyField(to='ItemShirtApp.size'),
        ),
    ]
